
TARGET = hello
TYPE = ps-exe

SRCS = \
hello.cpp \
fix16.c \
fix16_exp.c \
fix16_sqrt.c \
fix16_str.c \
fix16_trig.c \
fract32.c \
uint32.c \
mtxstuff.cpp \
mulmat0.o \
pushpop.o \
InitGeom.o \
sissycalls.o \
stdio.c \
filesystem.c \
misc.c \

CPPFLAGS = -Werror
CXXFLAGS = -std=c++20

# This will activate the PSYQo library and the rest of the toolchain.
include third_party/nugget/psyqo/psyqo.mk
